require 'guides_style_mbland/breadcrumbs'
require 'guides_style_mbland/generator'
require 'guides_style_mbland/navigation'
require 'guides_style_mbland/repository'
require 'guides_style_mbland/tags'
require 'guides_style_mbland/update'
require 'guides_style_mbland/version'

require 'jekyll_pages_api'
require 'jekyll_pages_api_search'
