require 'jekyll-theme-guides-mbland/breadcrumbs'
require 'jekyll-theme-guides-mbland/generator'
require 'jekyll-theme-guides-mbland/navigation'
require 'jekyll-theme-guides-mbland/repository'
require 'jekyll-theme-guides-mbland/tags'
require 'jekyll-theme-guides-mbland/update'
require 'jekyll-theme-guides-mbland/version'

require 'jekyll_pages_api'
require 'jekyll_pages_api_search'
